---
name: Create a GitHub Tag
on:
  workflow_dispatch:
    inputs:
      tag:
        required: true
permissions: {}
jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
        with:
          go-version: 1.22.4
          cache: true

      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2.1.0
        with:
          app_id: ${{secrets.APP_ID}}
          private_key: ${{secrets.APP_PRIVATE_KEY}}
          permissions: >-
            {"contents": "write"}
          repositories: >-
            ["suzuki-shunsuke/mkghtag"]

      - run: |
          go run ./cmd/mkghtag -msg "chore: release $TAG" "$TAG"
        env:
          TAG: ${{inputs.tag}}
          GITHUB_TOKEN: ${{steps.generate_token.outputs.token}}
