---
name: Create a GitHub Tag
on:
  workflow_dispatch:
    inputs:
      tag:
        required: true
permissions: {}
jobs:
  create-tag:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5.2.0
        with:
          go-version-file: go.mod
          cache: true

      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2.1.0
        with:
          app_id: ${{secrets.APP_ID}}
          private_key: ${{secrets.APP_PRIVATE_KEY}}
          permissions: >-
            {"contents": "write"}
          repositories: >-
            ["suzuki-shunsuke/mkghtag"]

      - run: |
          go run ./cmd/mkghtag -msg "chore: release $TAG" "$TAG"
        env:
          TAG: ${{inputs.tag}}
          GITHUB_TOKEN: ${{steps.generate_token.outputs.token}}
