---
name: push-main
on:
  push:
    branches:
      - main
permissions: {}
jobs:
  ossf-scorecard:
    uses: suzuki-shunsuke/ossf-scorecard-workflow/.github/workflows/ossf-scorecard.yaml@main
    permissions:
      security-events: write
      id-token: write
