---
name: Release
on:
  push:
    tags: [v*]
permissions: {}
jobs:
  release:
    uses: suzuki-shunsuke/go-release-workflow/.github/workflows/release.yaml@upload-provenance-by-ourselves-for-immutable-release
    with:
      go-version-file: go.mod
      aqua_version: v2.53.9
    permissions:
      contents: write
      id-token: write
      attestations: write
      actions: read
