---
name: Release
on:
  push:
    tags: [v*]
permissions: {}
jobs:
  release:
    uses: suzuki-shunsuke/go-release-workflow/.github/workflows/release.yaml@b0ca8ec80f84b3c54b707be91dba72ab763dffca # v3.0.1-0
    with:
      homebrew: true
      go-version-file: go.mod
      aqua_version: v2.48.0
      app_token_repositories: >-
        [
          "${{github.event.repository.name}}",
          "homebrew-${{github.event.repository.name}}",
          "scoop-bucket"
        ]
    secrets: inherit
    permissions:
      contents: write
      id-token: write
      attestations: write
      actions: read
