---
name: Verify Asset
run-name: Verify Asset ${{github.event.workflow_run.head_branch}}
on:
  workflow_run:
    workflows: ["Release"]
    types:
      - completed
jobs:
  verify-asset:
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    permissions:
      contents: read
      issues: write
    steps:
      # Notify the release failure
      - if: github.event.workflow_run.conclusion != 'success'
        env:
          GH_TOKEN: ${{github.token}}
          ISSUE_NUMBER: "687"
          URL: ${{github.event.workflow_run.html_url}}
        run: |
          gh issue comment "$ISSUE_NUMBER" -R "$GITHUB_REPOSITORY" -b ":x: [Release failed.]($URL)"

      - uses: suzuki-shunsuke/verify-go-asset-action@v0.1.0-0
        with:
          version: ${{github.event.workflow_run.head_branch}}

      # Notify this workflow run's failure
      - if: failure() || cancelled()
        env:
          GH_TOKEN: ${{github.token}}
          ISSUE_NUMBER: "687"
          URL: ${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}}
        run: |
          gh issue comment "$ISSUE_NUMBER" -R "$GITHUB_REPOSITORY" -b ":x: [Release verification failed.]($URL)"
