---
on:
  workflow_call:
    secrets:
      TAKUMI_GUARD_BOT_ID:
        required: true
permissions: {}
jobs:
  test:
    uses: suzuki-shunsuke/go-test-full-workflow/.github/workflows/test.yaml@embed-tools
    permissions:
      contents: read
      id-token: write
    secrets:
      TAKUMI_GUARD_BOT_ID: ${{secrets.TAKUMI_GUARD_BOT_ID}}

  integration-test:
    uses: $/.github/workflows/wc-test.yaml
    secrets:
      TAKUMI_GUARD_BOT_ID: ${{secrets.TAKUMI_GUARD_BOT_ID}}
    permissions:
      contents: read
      id-token: write
